# A sample TOML config file.

[styleguide]
container = "testthedocs/ttd-vale"
enabled = true

[spellcheck]
container = "testthedocs/ttd-spellcheck"
enabled = true

[toctree]
container = "testthedocs/ttd-toctree"
enabled = true
