baseURL = "http://example.org/"
languageCode = "en-us"
title = "Redactor"
theme = "hugo-apex-theme"
pygmentsCodeFences = true
pygmentsStyle = "dracula"

[params]
logo = "https://testthedocs.org/img/redactor-logo.png"
